import { UserProfile } from './types';

export const MOCK_PROFILE: UserProfile = {
  id: '1',
  name: 'Priya Sharma',
  age: 26,
  gender: 'female',
  height: "5'4\"",
  location: 'Mumbai, India',
  profession: 'Senior Software Engineer',
  education: 'B.Tech in Computer Science',
  religion: 'Hindu',
  caste: 'Brahmin',
  motherTongue: 'Hindi',
  bio: 'A technology enthusiast who loves traveling and exploring new cuisines. I value family traditions while maintaining a modern outlook on life. Looking for someone who is career-oriented yet family-focused.',
  photos: [
    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=500&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=500&auto=format&fit=crop',
  ],
  familyDetails: {
    fatherProfession: 'Retired Bank Manager',
    motherProfession: 'Homemaker',
    siblings: 1,
    familyValues: 'Moderate',
  },
  expectations: 'Looking for a kind-hearted, professional individual with similar cultural values and a zest for life.'
};

export const MOCK_PROFILES: UserProfile[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    age: 26,
    gender: 'female',
    height: "5'4\"",
    location: 'Mumbai, India',
    profession: 'Senior Software Engineer',
    education: 'B.Tech in Computer Science',
    religion: 'Hindu',
    caste: 'Brahmin',
    motherTongue: 'Hindi',
    bio: 'A technology enthusiast who loves traveling and exploring new cuisines.',
    photos: ['https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=500&auto=format&fit=crop'],
    familyDetails: { fatherProfession: 'Retired', motherProfession: 'Homemaker', siblings: 1, familyValues: 'Moderate' },
    expectations: 'A kind-hearted person.',
    isShortlisted: true,
  },
  {
    id: '2',
    name: 'Rahul Mehta',
    age: 29,
    gender: 'male',
    height: "5'11\"",
    location: 'Bangalore, India',
    profession: 'Software Architect',
    education: 'M.Tech IT',
    religion: 'Hindu',
    caste: 'Brahmin',
    motherTongue: 'Hindi',
    bio: 'Passionate about coding and outdoor sports.',
    photos: ['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=300&auto=format&fit=crop'],
    familyDetails: { fatherProfession: 'Engineer', motherProfession: 'Teacher', siblings: 2, familyValues: 'Liberal' },
    expectations: 'Career-oriented partner.',
    viewedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Siddharth Varma',
    age: 31,
    gender: 'male',
    height: "5'9\"",
    location: 'Delhi, India',
    profession: 'Product Manager',
    education: 'MBA Marketing',
    religion: 'Hindu',
    caste: 'Kshatriya',
    motherTongue: 'Hindi',
    bio: 'Enthusiastic about movies and photography.',
    photos: ['https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=300&auto=format&fit=crop'],
    familyDetails: { fatherProfession: 'Doctor', motherProfession: 'Chef', siblings: 0, familyValues: 'Moderate' },
    expectations: 'Looking for a compatible partner.',
    isHidden: true,
  }
];
